MarkdownBear: Set NODE_PATH for remark-lint
coala/docker-coala-base pull request #159
Opened 2017-04-18 08:25 UTC by jayvdb

remark-cli needs to find its plugins.  When invoked in `/coala-bears`
directory, Node automatically looks in `node_modules`.  However if
the docker image is used normally the working directory will not
be `/coala-bears`.  Setting NODE_PATH ensures that the plugins can
be found.

Related to https://github.com/coala/coala-bears/issues/1235

2017-04-18 12:36 UTC, underyx requested changes

2017-04-18 12:36 UTC, underyx commented on Dockerfile
> +ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en PATH=$PATH:/root/pmd-bin-5.4.1/bin:/root/dart-sdk/bin:/coala-bears/node_modules/.bin:/root/bakalint-0.4.0:/root/elm-format-0.18 NODE_PATH=/coala-bears/node_modu
Could you break this down into multiple lines with `\`?

2017-04-18 12:37 UTC, underyx commented
So you found it! 🎉 

Awesome :D

2017-04-18 14:16 UTC, underyx submitted a review, later dismissed

2017-04-18 14:16 UTC, underyx commented on .travis.yml
> +      coala-ci -I --bears MarkdownBear --files foo.md;
Isn't `coala-ci` deprecated? I think it should be `coala --non-interactive` instead.

2017-04-18 14:16 UTC, underyx commented on .travis.yml
> +      coala-ci -I --bears MarkdownBear --files foo.md;
Also I'm not sure what `-I` is, please use the long-form version? 😇

2017-04-19 08:05 UTC, sils commented
ack https://github.com/coala/docker-coala-base/pull/159/commits/499223554ff686e540c53badbfa45ccee07807a4

2017-04-19 08:11 UTC, sils commented
ack https://github.com/coala/docker-coala-base/pull/159/commits/3540ab3fa0b259b1bd5ff3b8b489ec6da7d2b2da

2017-04-19 08:12 UTC, sils commented
@rultor merge

2017-04-19 08:13 UTC, rultor commented
> @rultor merge

@sils OK, I'll try to merge now. You can check the progress of the merge [here](http://www.rultor.com/t/11430-295155082)

2017-04-19 08:14 UTC, merged

2017-04-19 08:15 UTC, rultor commented
> @rultor merge

@sils Done! FYI, the full log is [here](http://www.rultor.com/t/11430-295155082) (took me 1min)