.coafile: Add YAMLLintBear
coala/docker-coala-base pull request #186
Opened 2017-06-22 02:24 UTC by lherman-cs

Add YAMLLintBear to .coafile and
fix .travis.yml issues raised by coala

Closes https://github.com/coala/docker-coala-base/issues/183

2017-06-22 15:12 UTC, jayvdb requested changes

2017-06-22 15:12 UTC, jayvdb commented on .travis.yml
> +      bears/c_languages/CSharpLintBear.py
Can you please add indentation for arguments , so that it is easy to see where the next command starts.

2017-06-22 15:22 UTC, lherman-cs commented on .travis.yml
> +      bears/c_languages/CSharpLintBear.py
Yeah, sure.

2017-06-22 16:09 UTC, lherman-cs commented
Can someone help me to pass ci/dockercloud? I don't know what breaks it. Thanks

2017-06-22 16:10 UTC, lherman-cs commented
I'm so sorry. I miss clicked the button. Instead of "Comment," I clicked "Close and comment"

2017-06-29 20:28 UTC, jayvdb commented
@lherman-cs , can you rebase this patch (see the guides in our dev docs for how-to)

2017-07-04 17:24 UTC, jayvdb commented
Hi @lherman-cs , to rebase properly, you should archive your current branch , to a name like `old-pr-186`, then checkout master and sync your master with upstream master, then recreate the branch `hotfix/#183` and put your *one* commit on that branch.  Then repush.

2017-07-18 02:23 UTC, lherman-cs commented
Thanks, @jayvdb. I've fixed all the issues you mentioned before.

2017-11-01 07:53 UTC, anshumanv requested changes
Please check comments.

2017-11-01 07:53 UTC, anshumanv commented on .coafile
> +files = *.yml, hooks/*.yml
Please add a new line at file end.

2017-11-02 06:59 UTC, aashutoshrathi requested changes
Add `LineLengthBear` too.
and better change `[yml]` to `[YAML]`

2017-11-08 04:56 UTC, Monal5031 requested changes
@lherman-cs Please make changes as requested by other reviewers.
Also, squash your commits into one.

2020-06-19 01:21 UTC, closed without merging