Change maintainer to label maintainer in Dockerfile
coala/docker-coala-base pull request #246
Opened 2017-11-09 16:00 UTC by raju249

Fix for #245 
Changed it as mentioned in [doc](https://docs.docker.com/engine/reference/builder/#maintainer-deprecated)

2017-11-09 16:07 UTC, gureks requested changes
Please read the Writing Good Commits guide here: http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html
and change the shortlog and body accordingly

2017-11-09 18:02 UTC, jayvdb commented
This repo is broken at the moment, so this wont be merged until that is fixed.

However, please fix your commit message.

2017-11-10 07:35 UTC, raju249 commented
I have updated the commit message as per the guidelines.
Sorry that I missed it earlier.

Now, since this is blocked and won't be merged ..should I move on for `difficulty/low` issue or wait till this PR is merged ?

2017-11-10 12:54 UTC, prnvdixit requested changes
@raju249 
1. Please, mention issue reference in your ```Commit``` (you have mentioned it only in your PR description yet) :wink:
2. The length of Shortlog is more than that is specified https://coala.io/git 😄
3. You should mention the reasoning of changes in the commit description too - "This ensures that deprecation of "MAINTAINER" is handled." or something descriptive like this.

2017-11-10 12:57 UTC, prnvdixit commented
Also, I personally will recommend that you should move to difficulty/low issues only after this PR is atleast approved ("ack"ed) - If not merged, so that you have a better understanding of things to be kept in mind in general workflow and you get more reviews related to your code (than commit) on your low-PR. 👍

2017-11-10 12:58 UTC, raju249 commented
Thanks @prnvdixit 
Refactoring this commit 😃

2017-11-10 18:38 UTC, RaiVaibhav requested changes

2017-11-10 18:38 UTC, RaiVaibhav commented on Dockerfile
> +LABEL maintainer="Fabian Neuschmidt fabian@neuschmidt.de"
There have to some way to get the things directly by viewing it, here you did't give any difference between `persons` mail and his `name`, that's why we use `<>`.
Simply replace `"Fabian Neuschmidt fabian@neuschmidt.de"` to `"Fabian Neuschmidt <fabian@neuschmidt.de>"` will be more helpful, although your changes will work totally fine as we are not bounded here, we can set any `key` and his `value`.

2018-01-21 18:59 UTC, duskybomb commented
@Makman2 assign this to me.

2018-01-21 19:13 UTC, Makman2 commented
Closing due to inactivity.

2018-01-21 19:13 UTC, closed without merging