Dockerfile: Enable and fix Julia requirements install
coala/docker-coala-base pull request #37
Opened 2016-11-26 23:18 UTC by Mixih

Julia requirements were disabled before. This patch enables
the "Lint" julia package. It also install libpcre2-8-0
to fix julia which seems to be dynamically linked agaist this
specific version. This patch should enable docker building.

2016-11-26 23:29 UTC, sils commented
ack https://github.com/coala/docker-coala-base/pull/37/commits/4d48d0acbb231aca0e4cd4659f044d54e20c2898

2016-11-27 01:51 UTC, jayvdb requested changes

2016-11-27 01:51 UTC, jayvdb commented on Dockerfile
> +  libpcre2-8-0 \
this is the solution I came up with also.

2016-11-27 01:51 UTC, jayvdb commented on Dockerfile
> +RUN julia -e 'Pkg.add("'Lint'")'
This can be

```
RUN julia -e 'Pkg.add("Lint")'
```

2016-11-27 02:20 UTC, Mixih commented on Dockerfile
> +RUN julia -e 'Pkg.add("'Lint'")'
Thanks, forgot about that more elegant solution using string literals.

2016-11-27 02:20 UTC, Mixih commented
@jayvdb  Fixed

2016-11-27 02:24 UTC, jayvdb commented
Please add

"
Fixes https://github.com/coala/docker-coala-base/issues/18
Fixes https://github.com/coala/docker-coala-base/issues/35
"

2016-11-27 02:26 UTC, jayvdb approved these changes

2016-11-27 02:50 UTC, jayvdb commented
ack 34ffc84e09080

2016-11-27 02:50 UTC, jayvdb commented
@rultor merge

2016-11-27 02:51 UTC, rultor commented
> @rultor merge

@jayvdb OK, I'll try to merge now. You can check the progress of the merge [here](http://www.rultor.com/t/10122-263099068)

2016-11-27 02:52 UTC, rultor commented
> @rultor merge

@mixih @jayvdb Oops, I failed. You can see the full log [here](http://www.rultor.com/t/10122-263099068) (spent 9s)

```
+ set -e
+ set -o pipefail
++ dirname ./run.sh
+ cd .
+ echo 2440
+ echo '2.0-SNAPSHOT BUILD'
2.0-SNAPSHOT BUILD
+ date
Sun Nov 27 02:51:57 UTC 2016
+ uptime
 02:51:57 up 8 days,  9:06,  0 users,  load average: 1.86, 4.03, 6.06
+ fork=git@github.com:Mixih/docker-coala-base.git
+ fork_branch=FixJulia
+ head=git@github.com:coala/docker-coala-base.git
+ head_branch=master
+ pull_id=37
+ pull_title='Dockerfile: Enable and fix Julia requirements install'
+ vars=('--env=fork=git@github.com:Mixih/docker-coala-base.git' '--env=fork_branch=FixJulia' '--env=head=git@github.com:coala/docker-coala-base.git' '--env=head_branch=master' '--env=pull_id=37' '--env=pull_title=Dockerfile: Enable and fix Julia requirements install')
+ image=yegor256/rultor
+ directory=
+ scripts=()
+ container=coala_docker-coala-base_37
+ as_root=false
+ mkdir -p /home/rultor/.ssh
+ echo -e 'Host github.com\n\tStrictHostKeyChecking no\n'
+ chmod 600 /home/rultor/.ssh/config
+ git clone git@github.com:coala/docker-coala-base.git repo
Cloning into 'repo'...
+ cd repo
+ git config user.email me@rultor.com
+ git config user.name rultor
+ '[' -z '' ']'
+ '[' -e pom.xml ']'
+ '[' -e Gemfile ']'
+ '[' -e build.xml ']'
+ [[ -e build.sbt ]]
+ [[ -e project/Build.scala ]]
+ echo 'I can'\''t guess your build automation tool, see http://doc.rultor.com/basics.html'
I can't guess your build automation tool, see http://doc.rultor.com/basics.html
+ exit -1
'cid' file is absent, container wasn't started correctly

```

2016-11-27 02:55 UTC, merged