Fix build
coala/docker-coala-base pull request #44
Opened 2016-11-27 19:36 UTC by jayvdb

2016-11-27 19:37 UTC, jayvdb commented
Amend or cherry-pick, as useful.

2016-11-28 02:22 UTC, jayvdb commented on Dockerfile
>    jshint \
Should also remove jshint, if it is installed from openSUSE pkg

2016-11-28 02:22 UTC, jayvdb commented on Dockerfile
> -  alex \
I dont know why alex doeent pass. Actually only one of many tests fails :/

2016-11-28 03:43 UTC, AbdealiJK commented on Dockerfile
> -  alex \
@jayvdb Are you aware of the conflicting package name in the haskell compiler (ghc i think) called alex ? We've had issues before where the binary used is the wrong binary ...

2016-11-28 03:44 UTC, AbdealiJK commented
Question: Can we just use cib ? Is it not yet stable enough ?

2016-11-28 04:30 UTC, jayvdb commented on Dockerfile
> -  alex \
Ya, I did see that, but it is only one test that fails, and I doubt that `alex` is installed on this rather empty openSUSE image.  And fa70e924 added checks for this , and those tests pass.
A neater solution would be to disable only the one failing test.

2016-11-28 05:54 UTC, jayvdb commented
Circle node is v5.5.0 ; maybe we need to set node to v5 on openSUSE.

2016-11-28 15:35 UTC, Mixih commented
ack 
0e44724
000859c
785538c
3584d5d

2016-11-28 15:55 UTC, underyx commented
unack https://github.com/coala/docker-coala-base/pull/44/commits/000859cd0c3e85316ba932813d2f9f4bb3ee0982 until my comment is answered

feel free to reack it if you've seen my comment and think it's okay, @jayvdb

2016-11-28 15:55 UTC, underyx requested changes

2016-11-28 15:55 UTC, underyx commented on Dockerfile
> +    $(sed -ne '/~/{s/^[^"]*"//;s/".*"~/@/;s/",*//;p}' coala-bears/package.json)
😳 

How reliable is this? Couldn't we just do

```
WORKDIR /coala-bears/package.json
RUN npm install --global
```
?

2016-11-28 15:59 UTC, jayvdb commented on Dockerfile
> +    $(sed -ne '/~/{s/^[^"]*"//;s/".*"~/@/;s/",*//;p}' coala-bears/package.json)
No.  That installs `coala-bears` globally, and none of the dependencies are global.

There are a few alternatives, all ugly.

> How reliable is this?

We now have bear testing again, so we can see if it breaks.

2016-11-28 16:00 UTC, jayvdb commented
reack 000859c

2016-11-28 16:02 UTC, underyx approved these changes

2016-11-28 16:32 UTC, merged