Dockerfile: Remove unused packages
coala/docker-coala-base pull request #67
Opened 2016-12-22 12:00 UTC by yukiisbored

Bazaar, Mercurial, gfortran are removed because they're not used in
any way.

OpenJDK is replaced with a simple JRE package because PMD and
Checkstyle doesn't require JDK to run.

R-base is replaced with R-core since not every R packages is required
to run the linter.

Mono is removed because CSharpLintBear is unusable.

2016-12-22 12:15 UTC, robbyoconnor requested changes
Why not change the basd image to Alpine Linux?

2016-12-22 12:40 UTC, jayvdb commented
iirc gfortran is needed for R lintr.
bzr and hg are included so people can use VCS to fetch code to be checked.

2016-12-22 13:04 UTC, yukiisbored commented
@robbyoconnor requires a pretty massive change, see https://travis-ci.org/yukiisbored/docker-coala-base/builds/185973853. It generates a bigger image than openSUSE but that's because I just moved it to Alpine without tweaking.

2016-12-22 13:14 UTC, yukiisbored commented
@jayvdb I don't think lintr requires gfortran since there's no fortran code and there's no mention of `fortran` anywhere.

2016-12-22 14:20 UTC, jayvdb commented
If it isnt used, why is espeak installed in the CI for coala-bears?

Likewise for R, but see also https://travis-ci.org/coala/docker-coala-base/builds/186067098#L5707

2016-12-22 14:47 UTC, jayvdb commented
Removing mono should be a separate commit, closing the open issue about that.

The other changes look interesting.
How much size does this remove?

2016-12-22 14:56 UTC, yukiisbored commented
113 MBs

2016-12-22 18:53 UTC, jayvdb commented
> If it isnt used, why is espeak installed in the CI for coala-bears?

You were right about espeak.  See https://github.com/coala/coala-bears/pull/1188
Add another commit removing that (and again calculate how much this PR should have reduced the image size).

2016-12-22 18:54 UTC, jayvdb commented
ack 6dcf360
ack a533f9a

2016-12-22 18:57 UTC, jayvdb commented
unack 6dcf360

2016-12-22 19:03 UTC, jayvdb commented
Replacing `R-base` with `R-core` + `R-core-packages` is not having the effect described in the commit message.  The R packages installed are identical, probably due to cross-package "recommends" or something similar.
If you cant figure this R deps stuff, leave the R dependencies alone (and remove from the commit message).
The other removals that you have found are significant enough to be helpful for our end-users.  Thanks.

2016-12-23 03:29 UTC, yukiisbored commented
@jayvdb I've removed espeak and added how much this PR will reduce the image size.

2016-12-23 03:36 UTC, yukiisbored commented
@jayvdb I've made espeak into it's own commit

2016-12-23 03:43 UTC, jayvdb commented
ack 0253896
ack 4531b7a
ack 6c7c6c1

2016-12-23 04:20 UTC, jayvdb commented
@rultor merge

2016-12-23 04:21 UTC, rultor commented
> @rultor merge

@jayvdb OK, I'll try to merge now. You can check the progress of the merge [here](http://www.rultor.com/t/10382-268938742)

2016-12-23 04:21 UTC, merged

2016-12-23 04:22 UTC, rultor commented
> @rultor merge

@jayvdb Done! FYI, the full log is [here](http://www.rultor.com/t/10382-268938742) (took me 1min)